#!/usr/bin/env sh
set -eu

TARGET_URL="${1:-http://localhost:8080}"
REPORT_DIR="target/burp-reports"
REPORT_FILE="$REPORT_DIR/report.html"

mkdir -p "$REPORT_DIR"

STATUS="unreachable"
HTTP_CODE="000"
if command -v curl >/dev/null 2>&1; then
  HTTP_CODE="$(curl -k -s -o /tmp/petclinic-security-check.out -w '%{http_code}' "$TARGET_URL" || true)"
  if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 500 ]; then
    STATUS="reachable"
  fi
fi

cat > "$REPORT_FILE" <<EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Burp Suite Security Evidence</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 32px; color: #1f2933; }
    h1 { margin-bottom: 4px; }
    table { border-collapse: collapse; margin-top: 16px; min-width: 520px; }
    th, td { border: 1px solid #cbd5e1; padding: 8px 10px; text-align: left; }
    th { background: #f1f5f9; }
    code { background: #f8fafc; padding: 2px 4px; border-radius: 4px; }
  </style>
</head>
<body>
  <h1>Burp Suite Security Evidence</h1>
  <p>This Jenkins artifact records the security-test target used for the Burp Suite Community review.</p>
  <table>
    <tr><th>Target URL</th><td><code>$TARGET_URL</code></td></tr>
    <tr><th>HTTP status</th><td>$HTTP_CODE</td></tr>
    <tr><th>Target reachability</th><td>$STATUS</td></tr>
    <tr><th>Generated by</th><td>scripts/run-burp-report.sh</td></tr>
  </table>
  <h2>Manual Burp Community demo steps</h2>
  <ol>
    <li>Start the Burp container with <code>docker compose -f docker-compose.devsecops.yml up -d burpsuite</code>.</li>
    <li>Connect a VNC client to <code>localhost:5900</code>.</li>
    <li>Use Burp's browser or proxy to browse the PetClinic target URL.</li>
    <li>Show Proxy HTTP history and any issue notes collected during the walkthrough.</li>
  </ol>
  <p>Burp Suite Community does not provide the same headless automated scanner/report exporter as Burp Suite Professional. This artifact gives Jenkins a published security evidence report while the GUI Burp review is demonstrated separately.</p>
</body>
</html>
EOF

echo "Security evidence report written to $REPORT_FILE"
