[production]
# Replace this with the production VM IP or DNS name.
# Example:
# real-vm ansible_host=192.168.56.20 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/petclinic_vm
real-vm ansible_host=CHANGE_ME ansible_user=ubuntu

[production:vars]
ansible_python_interpreter=/usr/bin/python3
