name: Java CI con Maven (Spring PetClinic)

# 1. Cuándo se ejecuta el flujo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 2. Qué tareas va a realizar
jobs:
  build-and-test:
    runs-on: ubuntu-latest # Levanta un servidor virtual con Linux Ubuntu

    steps:
    # Paso A: Clonar el código del repositorio en el servidor virtual
    - name: Checkout del código
      uses: actions/checkout@v4

    # Paso B: Instalar y configurar el entorno de ejecución de Java
    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven' # Guarda en caché las dependencias para que el build sea más rápido

    # Paso C: Dar permisos de ejecución al empaquetador de Maven (Wrapper)
    - name: Otorgar permisos al script de Maven
      run: chmod +x mvnw

    # Paso D: Compilar el código y ejecutar las pruebas automatizadas (Simulación de Integración)
    - name: Construir y ejecutar pruebas con Maven
      run: ./mvnw clean verify