name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Maven Build
        uses: ./.github/actions/maven-java-build
      - name: Docker Build & Push
        uses: ./.github/actions/docker-build-push