name: Universal CI

on:
  push:
    branches:
      - main
      - feature/github-actions fe

jobs:

  detect:
    runs-on: ubuntu-latest

    outputs:
      language: ${{ steps.detect.outputs.language }}

    steps:
      - uses: actions/checkout@v4

      - id: detect
        run: |
          chmod +x scripts/detect.sh
          scripts/detect.sh

  build:
    needs: detect
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Login to JFrog Docker Registry
        run: |
          docker login ${{ secrets.JFROG_URL }} \
          -u ${{ secrets.JFROG_USERNAME }} \
          -p ${{ secrets.JFROG_PASSWORD }}

      - name: Build Java
        if: needs.detect.outputs.language == 'java'
        run: |
          docker run --rm \
          -v $PWD:/workspace \
          -w /workspace \
          trial2zs76n.jfrog.io/docker-local/java-builder:1.0 \
          mvn clean package

      - name: Build Python
        if: needs.detect.outputs.language == 'python'
        run: |
          docker run --rm \
          -v $PWD:/workspace \
          -w /workspace \
          trial2zs76n.jfrog.io/docker-local/python-builder:1.0 \
          bash -c "pip install -r requirements.txt"

      - name: Build Go
        if: needs.detect.outputs.language == 'go'
        run: |
          docker run --rm \
          -v $PWD:/workspace \
          -w /workspace \
          trial2zs76n.jfrog.io/docker-local/go-builder:1.0 \
          go build

  publish:
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit 