---
on:
    push:
       branches:
        - main:
    workflow_dispatch:    # manual trigger
jobs:
    maven:
        runs-on: [ 'ubuntu_latest' ]
        steps:
         - name: checkout the code
           uses: actions/checkout@v4
         - name: build code
           uses: mvn package               