name: "Frogbot Repo Scan and Fix"
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight. Customize as needed.
  workflow_dispatch: # Allows manual trigger from the Actions tab.

permissions:
  contents: write
  pull-requests: write

jobs:
  frogbot-repo-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # Speeds up subsequent scans by caching dependencies
     
      - name: Run Frogbot Repo Scan
        uses: jfrog/frogbot@v2
        with:
          frogbot-command: "scan-repository"
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ vars.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ vars.GITHUB_TOKEN }}
