name: "Frogbot Security Scan"

on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write
  security-events: write

jobs:
  pr-security-scan:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: jfrog/frogbot@v3
        env:
          JF_GIT_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
          JF_GIT_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
          JF_URL: ${{ secrets.JFROG_REGISTRY }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_OIDC_PROVIDER_NAME: "github"
          FROGBOT_CMD: "scan-pull-request"
          JF_GIT_REPO: ${{ github.event.repository.name }}
          JF_GIT_OWNER: ${{ github.repository_owner }}
          JF_GIT_PROVIDER: 'github'

  repository-scan:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: jfrog/frogbot@v3
        env:
          JF_GIT_BASE_BRANCH: ${{ github.ref_name }}
          JF_URL: ${{ secrets.JFROG_REGISTRY }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_OIDC_PROVIDER_NAME: "github"
          FROGBOT_CMD: "scan-repository"
          JF_GIT_PROVIDER: 'github'
          JF_GIT_OWNER: ${{ github.repository_owner }}
          JF_GIT_REPO: ${{ github.event.repository.name }}