name: "Frogbot Scan and Fix"
on:
  push:
    branches: [ "main" ]
permissions:
  contents: write
  pull-requests: write
  security-events: write
  id-token: write
jobs:
  create-fix-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JFROG_REGISTRY }}
        with:
          oidc-provider-name: github-frogbot

      - uses: jfrog/frogbot@5d9c42c30f1169d8be4ba5510b40e75ffcbbc2a9  # v2.21.2
        env:
          JF_URL: https://${{ secrets.JFROG_REGISTRY }}
          JF_OIDC_PROVIDER_NAME: "github-frogbot"
          FROGBOT_CMD: "scan-and-fix"
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}