name: Spring PetClinic CI

on:
  push:
    branches:
      -main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello DevOps"
      -name: Print
       run: echo "Hi"